version: '3.7'
services:
  mysql:
    container_name: mysql
    build:
      context: ./.docker/mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=hardware
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3316:3306"
  apache_php:
    container_name: symfony-vue
    build:
      context: ./.docker/apache
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:192.168.1.105"
    links:
      - "mysql:db_mysql"
    depends_on:
      mysql:
        condition: service_started
